#this is designed to ping my website in order to keep it online and quickly accessible and to stop the underlying server from sleeping
import os
import time

for x in range(1, 10): #how many time you want it to repeat
  hostname = "www.frazeranderson.co.uk" #website address
  response = os.system("ping " + hostname) #command line code
  if x<10:
    time.sleep(5760) #in seconds

#if a printed response aside from that generated by the command line is required
#if response == 0:
#  print hostname, 'is up!'
#else:
#  print hostname, 'is down!'

